_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "8":
                - 2
                - 5
            "12": 0.19.1
            "13": linux-x86_64
dataset:
    value: GSE54651/liver
dropout:
    value: 0.1
embed_dim:
    value: 128
lr:
    value: 0.0005
num_epochs:
    value: 200
num_genes:
    value: 10
num_pathways:
    value: 44
